# Generated by Django 5.2.4 on 2025-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('green_cover', models.FloatField()),
                ('pollution_index', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('eco_cost', models.FloatField()),
            ],
        ),
    ]
